language: c
env:
  - OCAML_VERSION=4.06.0
addons:
  apt:
    sources:
      - avsm
    packages:
      - opam
      - time
cache:
  directories:
    - $HOME/.opam
before_install:
  - export OPAMYES=1
  - export OPAMVERBOSE=1
  - export CONFIGUREFLAGS=--enable-tests
  - opam init
  - opam switch ${OCAML_VERSION}
  - eval `opam config env`
  - opam pin add --no-action dedukti .
  - opam install --deps-only dedukti
install:
  - make build
script:
  - make test
  - chmod u+x tests/external_tests.sh
  - tests/external_tests.sh
os:
  - linux
notifications:
  email:
    - genestier@lsv.fr
branches:
  only:
    - adding_lib
