dist: trusty
language: c

os:
  - linux

branches:
  only:
    - master

cache:
  directories:
  - $HOME/.opam

env:
  global:
  - OPAMJOBS="2"
  - OPAMYES="true"
  - OPAMVERBOSE="true"
  matrix:
  - OCAML_VERSION=4.03.0
  - OCAML_VERSION=4.03.0+flambda
  - OCAML_VERSION=4.04.1
  - OCAML_VERSION=4.04.2
  - OCAML_VERSION=4.05.0
  - OCAML_VERSION=4.06.0
  - OCAML_VERSION=4.06.0+flambda
  - OCAML_VERSION=4.06.1
  - OCAML_VERSION=4.07.1
  - OCAML_VERSION=4.08.1
  - OCAML_VERSION=4.09.0

before_install:
  # Obtain and install opam locally.
  - sudo wget https://github.com/ocaml/opam/releases/download/2.0.5/opam-2.0.5-x86_64-linux -O /usr/bin/opam
  - sudo chmod 755 /usr/bin/opam
  # Initialize the switch.
  - opam init -a --disable-sandboxing --compiler="$OCAML_VERSION"
  - opam update
  - opam switch "$OCAML_VERSION"
  - eval $(opam env)
  - opam pin add --no-action dedukti .
  - opam install --deps-only dedukti

install:
  - make
  - make install

script:
  - make tests
  - if [[ "$OCAML_VERSION" == "4.09.0" ]];
      then
        if [[ "$TRAVIS_EVENT_TYPE" == "cron" ]];
          then make full_tests;
          else make light_tests;
        fi;
    fi

notifications:
  email:
    - dedukti-commits@lists.gforge.inria.fr
