#!/bin/sh

COQINE="../bin/coqine"

for i in Notations Logic Datatypes Peano Specif Wf
do
    echo -n "CoqInE $i : "
    if $COQINE /usr/lib/coq/theories/Init/$i.vo 2> regression.log 
    then echo "ok."
    else echo "failed."
    fi
    echo -n "Checking $i : "
    if (dkparse Coq_Init_$i.dk | lua) 2> regression.log
    then echo "ok."
    else echo "failed."
    fi
    echo -n "Compiling $i : "
    if dkparse -c Coq_Init_$i.dk > Coq_Init_$i.lua 2> regression.log
    then echo "ok."
    else echo "failed."
    fi
done
