#!/bin/sh

COQINE_ROOT=/home/burel/projets/coqine
COQ_LIB=/usr/lib/coq/theories/
LIBS=$COQ_LIB*
INCLUDE=/usr/lib/coq/contrib/

rm depend

for i in $LIBS
do
    for t in $i/*.vo
    do
	if $COQINE_ROOT/bin/coqine --root Coq -I $INCLUDE -I $COQ_LIB $t 
	then echo "Success : $t"
	else echo "Failed : $t"
	fi
	$COQINE_ROOT/bin/make_deps --root Coq -I $INCLUDE -I $COQ_LIB $t >> depend
    done
done
