#!/bin/sh

COQ_LIB=/usr/lib/coq/theories/
LIBS=$COQ_LIB*
INCLUDE=/usr/lib/coq/contrib/

rm Coq_lib/depend

for i in $LIBS
do
    for t in $i/*.vo
    do
	if bin/coqine --root Coq -I $INCLUDE -I $COQ_LIB $t > Coq_lib/Coq_`basename $i`_`basename $t .vo`.dk
	then echo "Success : $t"
	else echo "Failed : $t"
	fi
	bin/make_deps --root Coq -I $INCLUDE -I $COQ_LIB $t >> Coq_lib/depend
    done
done
