#!/bin/sh

COQINE="../bin/coqine --root Coq -I /usr/lib/coq/theories"

for i in Logic Datatypes Peano Wf
do
    echo -n "CoqInE $i : "
    if $COQINE /usr/lib/coq/theories/Init/$i.vo > $i.dk 2> regression.log 
    then echo "ok."
    else echo "failed."
    fi
    echo -n "Dedukti $i : "
    if dedukti $i.dk 2> regression.log
    then echo "ok."
    else echo "failed."
    fi
    echo -n "Compiling $i : "
    if ../scripts/compile $i.dko &> regression.log
    then echo "ok."
    else echo "failed."
    fi
done

echo -n "Checking Logic : "
if dkrun Logic.dko Coq1univ.dko &> regression.log
then echo "ok."
else echo "failed."
fi
echo -n "Checking Datatypes : "
if dkrun Datatypes.dko Coq1univ.dko Logic.dko &> regression.log
then echo "ok."
else echo "failed."
fi
echo -n "Checking Peano : "
if dkrun Peano.dko Coq1univ.dko Logic.dko Datatypes.dko &> regression.log
then echo "ok."
else echo "failed."
fi
echo -n "Checking Wf : "
if dkrun Wf.dko Coq1univ.dko Logic.dko Datatypes.dko &> regression.log
then echo "ok."
else echo "failed."
fi
